/**
 * Tests for the RFC 4122 v5 UUID helper used to derive `<podcast:guid>`.
 */
import { describe, it, expect } from 'vitest';
import { uuidv5 } from '../src/uuid.js';

const DNS_NAMESPACE = '6ba7b810-9dad-11d1-80b4-00c04fd430c8';
const URL_NAMESPACE = '6ba7b811-9dad-11d1-80b4-00c04fd430c8';

const UUID_V5_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

describe('uuidv5', () => {
  it('is deterministic: same input yields the same UUID', () => {
    const a = uuidv5('www.example.com', DNS_NAMESPACE);
    const b = uuidv5('www.example.com', DNS_NAMESPACE);
    expect(a).toBe(b);
  });

  it('differs across namespaces for the same name', () => {
    const dns = uuidv5('www.example.com', DNS_NAMESPACE);
    const url = uuidv5('www.example.com', URL_NAMESPACE);
    expect(dns).not.toBe(url);
    expect(dns).toMatch(UUID_V5_REGEX);
    expect(url).toMatch(UUID_V5_REGEX);
  });

  it('matches reference v5 vectors (verified against Python stdlib `uuid.uuid5`)', () => {
    // These vectors were generated by Python 3 stdlib:
    //   >>> import uuid
    //   >>> uuid.uuid5(uuid.NAMESPACE_DNS, "www.example.com")
    //   UUID('2ed6657d-e927-568b-95e1-2665a8aea6a2')
    //   >>> uuid.uuid5(uuid.NAMESPACE_DNS, "python.org")
    //   UUID('886313e1-3b8a-5372-9b90-0c9aee199e5d')
    expect(uuidv5('www.example.com', DNS_NAMESPACE)).toBe(
      '2ed6657d-e927-568b-95e1-2665a8aea6a2'
    );
    expect(uuidv5('python.org', DNS_NAMESPACE)).toBe(
      '886313e1-3b8a-5372-9b90-0c9aee199e5d'
    );
  });
});
