/**
 * Published-feed health check.
 *
 * Checks what listeners actually receive: fetches the live RSS feeds from
 * GitHub Pages and asserts they contain the current conference's audio by
 * the time it is due. Any failure upstream (site change, scraper bug, broken
 * workflow, failed Pages deploy) shows up here as a late or missing episode.
 *
 * Also warns ahead of each conference when no channel art has been chosen
 * for it (config/conference-image-overrides.json in the checkout): channel
 * art only changes deliberately (channel-art.ts), so it must be set in time.
 *
 * Read-only. Runs from its own workflow so a fault here can never stop the
 * feed pipeline itself.
 *
 * Usage: npx tsx src/check-feed-health.ts [--base-url URL] [--now ISO]
 * Exit code 1 when any feed fails.
 */

import { pathToFileURL } from 'node:url';
import { ImageOverrides, loadImageOverrides, overrideKey } from './channel-art.js';

export const FEEDS = [
  { language: 'eng', file: 'audio.xml' },
  { language: 'spa', file: 'audio-es.xml' },
  { language: 'por', file: 'audio-pt.xml' },
] as const;

const DEFAULT_BASE_URL = 'https://nanodba.github.io/gc_podcast';

const DAY_MS = 24 * 60 * 60 * 1000;

/** Full-session episodes expected per conference (Sat/Sun morning + afternoon). */
export const EXPECTED_SESSIONS = 4;
/** Recent conferences have 33-40 talks; fewer than this means talks are missing. */
export const MIN_TALKS = 25;
/** Full-session audio is due from this many days after Saturday (Tuesday 00:00 UTC). */
export const SESSIONS_DUE_DAYS = 3;
/** Per-talk audio usually lands within a week; due from Saturday + this many days. */
export const TALKS_DUE_DAYS = 10;
/** The pipeline runs 3x daily in the conference window; older than this means it stopped. */
export const MAX_BUILD_AGE_HOURS = 36;
/** Conference window during which feed freshness is enforced (days after Saturday). */
export const WINDOW_DAYS = 14;
/** Channel art for the next conference must be chosen this many days before its Saturday. */
export const CHANNEL_ART_LEAD_DAYS = 10;

export interface FeedItem {
  guid: string;
  enclosureUrl: string;
}

export interface ParsedFeed {
  lastBuildDate?: Date;
  items: FeedItem[];
}

export interface HealthResult {
  ok: boolean;
  failures: string[];
  notes: string[];
}

/** General Conference is held on the first full weekend: the first Saturday of April/October. */
export function conferenceSaturday(year: number, month: 4 | 10): Date {
  const first = new Date(Date.UTC(year, month - 1, 1));
  const offset = (6 - first.getUTCDay() + 7) % 7;
  return new Date(Date.UTC(year, month - 1, 1 + offset));
}

/** The most recent conference whose Saturday is on or before `now`. */
export function currentConference(now: Date): { year: number; month: 4 | 10; saturday: Date } {
  const year = now.getUTCFullYear();
  const candidates: { year: number; month: 4 | 10 }[] = [
    { year, month: 10 },
    { year, month: 4 },
    { year: year - 1, month: 10 },
  ];
  for (const c of candidates) {
    const saturday = conferenceSaturday(c.year, c.month);
    if (saturday.getTime() <= now.getTime()) return { ...c, saturday };
  }
  throw new Error('unreachable: October of the previous year is always in the past');
}

/** The next conference whose Saturday has not yet ended at `now`. */
export function upcomingConference(now: Date): { year: number; month: 4 | 10; saturday: Date } {
  const year = now.getUTCFullYear();
  const candidates: { year: number; month: 4 | 10 }[] = [
    { year, month: 4 },
    { year, month: 10 },
    { year: year + 1, month: 4 },
  ];
  for (const c of candidates) {
    const saturday = conferenceSaturday(c.year, c.month);
    if (saturday.getTime() + DAY_MS > now.getTime()) return { ...c, saturday };
  }
  throw new Error('unreachable: April of the next year is always in the future');
}

/**
 * From CHANNEL_ART_LEAD_DAYS before the conference Saturday through that
 * Saturday, returns a failure message when any feed language lacks a
 * channel-art override for the conference; otherwise undefined.
 */
export function channelArtWarning(now: Date, overrides: ImageOverrides): string | undefined {
  const conf = upcomingConference(now);
  if (now.getTime() < conf.saturday.getTime() - CHANNEL_ART_LEAD_DAYS * DAY_MS) return undefined;
  const missing = FEEDS.map((f) => overrideKey(conf.year, conf.month, f.language)).filter(
    (k) => !overrides[k],
  );
  if (missing.length === 0) return undefined;
  const label = `${conf.year}-${String(conf.month).padStart(2, '0')}`;
  return `set channel art for ${label} before the conference: missing ${missing.join(', ')}`;
}

/** Minimal RSS reader for the fields the check needs (feeds are generated by rss-generator.ts). */
export function parseFeed(xml: string): ParsedFeed {
  const build = /<lastBuildDate>([^<]+)<\/lastBuildDate>/.exec(xml);
  const items: FeedItem[] = [];
  for (const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/g)) {
    const guid = /<guid[^>]*>([^<]*)<\/guid>/.exec(m[1])?.[1] ?? '';
    const enclosureUrl = /<enclosure[^>]*\burl="([^"]*)"/.exec(m[1])?.[1] ?? '';
    items.push({ guid, enclosureUrl });
  }
  const lastBuildDate = build ? new Date(build[1]) : undefined;
  return {
    lastBuildDate: lastBuildDate && !isNaN(lastBuildDate.getTime()) ? lastBuildDate : undefined,
    items,
  };
}

/** Pure verdict for one feed at time `now`. */
export function evaluateFeed(feed: ParsedFeed, now: Date): HealthResult {
  const failures: string[] = [];
  const notes: string[] = [];

  if (feed.items.length === 0) failures.push('feed has no items');

  const blank = feed.items.filter((i) => !/^https:\/\/\S+$/.test(i.enclosureUrl));
  if (blank.length > 0)
    failures.push(`${blank.length} item(s) with a missing or non-https enclosure`);

  const guids = feed.items.map((i) => i.guid);
  const dupes = guids.filter((g, idx) => guids.indexOf(g) !== idx);
  if (dupes.length > 0) failures.push(`duplicate GUIDs: ${[...new Set(dupes)].join(', ')}`);

  const conf = currentConference(now);
  const label = `${conf.year}-${String(conf.month).padStart(2, '0')}`;
  const prefix = `gc-${conf.year}-${conf.month}-`;
  const confItems = feed.items.filter((i) => i.guid.startsWith(prefix));
  const sessions = confItems.filter((i) => i.guid.endsWith('-full')).length;
  const talks = confItems.length - sessions;
  const daysSince = (now.getTime() - conf.saturday.getTime()) / DAY_MS;

  if (daysSince <= WINDOW_DAYS) {
    if (!feed.lastBuildDate) {
      failures.push('lastBuildDate missing or unparseable');
    } else {
      const ageHours = (now.getTime() - feed.lastBuildDate.getTime()) / (60 * 60 * 1000);
      if (ageHours > MAX_BUILD_AGE_HOURS) {
        failures.push(
          `feed not rebuilt for ${Math.round(ageHours)}h during the conference window (pipeline stopped?)`,
        );
      }
    }
  }

  if (daysSince >= SESSIONS_DUE_DAYS && sessions < EXPECTED_SESSIONS) {
    failures.push(`${label}: ${sessions}/${EXPECTED_SESSIONS} full-session episodes (due by now)`);
  }
  if (daysSince >= TALKS_DUE_DAYS && talks < MIN_TALKS) {
    failures.push(`${label}: ${talks} talk episodes, expected at least ${MIN_TALKS} (due by now)`);
  }
  notes.push(
    `${label}: ${sessions}/${EXPECTED_SESSIONS} sessions, ${talks} talks, day ${Math.floor(daysSince)} after Saturday`,
  );

  return { ok: failures.length === 0, failures, notes };
}

/** HEAD each URL (GET fallback); returns the ones that do not answer 2xx/3xx. */
async function deadEnclosures(urls: string[]): Promise<string[]> {
  const dead: string[] = [];
  for (const url of urls) {
    let ok = false;
    for (const method of ['HEAD', 'GET']) {
      try {
        const res = await fetch(url, {
          method,
          redirect: 'follow',
          headers: method === 'GET' ? { Range: 'bytes=0-0' } : {},
          signal: AbortSignal.timeout(20_000),
        });
        await res.body?.cancel();
        if (res.status < 400) {
          ok = true;
          break;
        }
      } catch {
        // try the next method
      }
    }
    if (!ok) dead.push(url);
  }
  return dead;
}

/** Newest enclosures to spot-check per feed; enough to catch a CDN change, cheap per run. */
const ENCLOSURE_SAMPLE = 8;

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const arg = (name: string) => {
    const i = args.indexOf(name);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const baseUrl = (arg('--base-url') ?? DEFAULT_BASE_URL).replace(/\/$/, '');
  const now = arg('--now') ? new Date(arg('--now') as string) : new Date();

  let anyFailed = false;
  for (const { language, file } of FEEDS) {
    const url = `${baseUrl}/${file}`;
    let result: HealthResult;
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(30_000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const feed = parseFeed(await res.text());
      result = evaluateFeed(feed, now);
      const dead = await deadEnclosures(
        feed.items.slice(0, ENCLOSURE_SAMPLE).map((i) => i.enclosureUrl),
      );
      if (dead.length > 0) {
        result.failures.push(`unreachable enclosures: ${dead.join(' ')}`);
        result.ok = false;
      }
    } catch (err) {
      result = {
        ok: false,
        failures: [`could not fetch ${url}: ${err instanceof Error ? err.message : String(err)}`],
        notes: [],
      };
    }
    anyFailed ||= !result.ok;
    console.log(`[${language}] ${result.ok ? 'OK' : 'FAIL'} ${url}`);
    for (const n of result.notes) console.log(`  ${n}`);
    for (const f of result.failures) console.log(`  FAIL: ${f}`);
  }

  const artWarning = channelArtWarning(now, await loadImageOverrides());
  anyFailed ||= artWarning !== undefined;
  console.log(`[channel-art] ${artWarning ? 'FAIL' : 'OK'} config/conference-image-overrides.json`);
  if (artWarning) console.log(`  FAIL: ${artWarning}`);
  process.exitCode = anyFailed ? 1 : 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
